# SALT 0.11 training config for the ATLAS tagger
#
# Requires SALT to be checked out at tagger/salt/ (see README).
# Adjust data.train_file / val_file / test_file to your H5 paths. (not needed if ran with train.sh)

name: atlas_jet_classification

model:
  lrs_config:
    initial: 1e-7
    max: 1e-3           
    end: 1e-6
    pct_start: 0.05
    weight_decay: 1e-10

  model:
    class_path: salt.models.SaltModel
    init_args:
      init_nets:
        - input_name: jets
          attach_global: false # somehow prevents features from being duplicated
          dense_config:
            input_size: 8
            hidden_layers: [10, 10, 10]
            output_size: 10
            activation: &activation ReLU
      
      encoder: null
      pool_net: null

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jets_classification
                input_name: jets
                label: a_jet
                class_names: [a_jet]
                use_class_dict: false
                loss:
                  class_path: torch.nn.BCEWithLogitsLoss
                  init_args:
                    pos_weight: [1.0] # ADD REWEIGHTING HERE [BKG,SIG]
                dense_config:
                  input_size: 10
                  output_size: 1  
                  hidden_layers: []
                  activation: *activation

data:
  train_file: path/to/train/file
  val_file:   path/to/val/file
  test_file:  path/to/test/file
  norm_dict:  norm_dict_classification_atlas.yaml
  class_dict: null
  batch_size: 100
  num_workers: 20
  num_train: -1
  num_val: -1
  num_test: -1
  # for handeling very large/negative numbers 
  non_finite_to_num: true
  ignore_finite_checks: false  # Keeps guardrails up but fixes the numbers



  labels:
    jets:
      - a_jet

  input_map:
    jets: jets

  variables:
    jets:
      - atlas_regression_a_mass
      - trk_multi
      - lead_trk_rel_system_pt
      - lead_trk_dr
      - angularity_n2
      - U1_0p7
      - M2_0p3
      - tau2


trainer:
  max_epochs: 29
  accelerator: auto   # set to "gpu" on NAF
  devices: 1
  log_every_n_steps: 50
  default_root_dir: atlas_logs

  logger:
    class_path: lightning.pytorch.loggers.CometLogger
    init_args:
      project_name: atlas_2025
      save_dir: atlas_logs
      offline: false
      display_summary_level: 0

  callbacks:
    - class_path: salt.callbacks.Checkpoint
      init_args:
        monitor_loss: val/jets_classification_loss
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args: { refresh_rate: 50 }
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args: { max_depth: 2 }
