name: atlas_mass_regression

model:
  lrs_config:
    initial: 1e-7
    max: 1e-3           
    end: 1e-6
    pct_start: 0.05
    weight_decay: 1e-11

  model:
    class_path: salt.models.SaltModel
    init_args:
      init_nets:
        - input_name: jets
          attach_global: false
          dense_config:
            input_size: 7
            hidden_layers: [35, 35, 35, 35]
            output_size: 35
            activation: &activation ReLU

      encoder: null
      pool_net: null

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.RegressionTask
              init_args:
                name: jet_regression
                input_name: jets
                targets: truth_a_mass
                loss: HuberLoss
                dense_config:
                  input_size: 35
                  output_size: 1  
                  hidden_layers: []
                  activation: *activation

data:
  train_file: path/to/train/file
  val_file:   path/to/val/file
  test_file:  path/to/test/file
  norm_dict:  atlas_2025_model/configs/norm_dict.yaml
  class_dict: null
  batch_size: 160
  num_workers: 20
  num_train: -1
  num_val: -1
  num_test: -1
  # for handeling very large/negative numbers 
  non_finite_to_num: true
  ignore_finite_checks: false  # Keeps guardrails up but fixes the numbers


  input_map:
    jets: jets

  variables:
    jets:
      - trk_multi
      - lead_trk_rel_system_pt
      - lead_trk_dr
      - angularity_n2
      - U1_0p7
      - M2_0p3
      - tau2

trainer:
  max_epochs: 50
  accelerator: auto
  devices: 1
  log_every_n_steps: 50
  default_root_dir: atlas_logs

  logger:
    class_path: lightning.pytorch.loggers.CometLogger
    init_args:
      project_name: atlas_2025
      save_dir: logs
      offline: false
      display_summary_level: 0

  callbacks:
    - class_path: salt.callbacks.Checkpoint
      init_args:
        monitor_loss: val/jet_regression_loss
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args: { refresh_rate: 50 }
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args: { max_depth: 2 }
